#!/usr/bin/env python3
"""
gen_vectors.py -- build RSIU test vectors from the REAL raytrace scene.

Rather than inventing numbers, we take the exact camera and spheres that
`bm_raytrace/run_benchmark.py` builds, run the reference intersection maths in
double precision, and emit:

  * vectors.vh  -- Q16.16 operands + expected results for the Verilog testbench
  * a printed error table quantifying what Q16.16 costs versus double

Run:  python3 hw/tb/gen_vectors.py
"""
import math
import os

FRAC = 16
ONE = 1 << FRAC


def to_q(x):
    """double -> Q16.16 two's-complement, as a 32-bit unsigned pattern."""
    v = int(round(x * ONE))
    if v < 0:
        v += 1 << 32
    return v & 0xFFFFFFFF


def from_q(u):
    """Q16.16 bit pattern -> double."""
    if u & 0x80000000:
        u -= 1 << 32
    return u / ONE


def normalize(v):
    m = math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2])
    return (v[0] / m, v[1] / m, v[2] / m)


def intersection_time(centre, radius, ray_p, ray_v):
    """Reference implementation -- identical arithmetic to Sphere.intersectionTime."""
    cx = centre[0] - ray_p[0]
    cy = centre[1] - ray_p[1]
    cz = centre[2] - ray_p[2]
    v = cx * ray_v[0] + cy * ray_v[1] + cz * ray_v[2]
    disc = radius * radius - (cx * cx + cy * cy + cz * cz - v * v)
    if disc < 0:
        return None
    return v - math.sqrt(disc)


def main():
    # --- the scene exactly as bench_raytrace() builds it -------------------
    position = (0.0, 1.8, 10.0)      # Scene.position
    looking_at = (0.0, 3.0, 0.0)     # s.lookAt(Point(0, 3, 0))
    ray_p = position
    ray_v = normalize((looking_at[0] - position[0],
                       looking_at[1] - position[1],
                       looking_at[2] - position[2]))

    spheres = [((1.0, 3.0, -10.0), 2.0)]
    for y in range(6):
        spheres.append(((-3.0 - y * 0.4, 2.3, -5.0), 0.4))
    # a deliberate miss and a sphere the ray starts inside, to exercise both
    # the disc < 0 path and a negative-t hit
    spheres.append(((8.0, 8.0, -5.0), 0.5))
    spheres.append(((0.0, 1.8, 9.0), 3.0))

    print("Ray origin    : (%.6f, %.6f, %.6f)" % ray_p)
    print("Ray direction : (%.9f, %.9f, %.9f)" % ray_v)
    print()
    print("%-3s %-26s %-7s %-14s %-14s %-10s" %
          ("id", "centre", "radius", "t (double)", "t (Q16.16)", "abs err"))
    print("-" * 82)

    lines = []
    n_hit = 0
    max_err = 0.0
    for i, (c, r) in enumerate(spheres):
        t = intersection_time(c, r, ray_p, ray_v)
        hit = 1 if t is not None else 0
        if hit:
            n_hit += 1
            tq = to_q(t)
            err = abs(from_q(tq) - t)
            max_err = max(max_err, err)
            shown_t, shown_q, shown_e = "%.9f" % t, "%.9f" % from_q(tq), "%.2e" % err
        else:
            tq = 0
            shown_t, shown_q, shown_e = "miss", "miss", "-"
        print("%-3d (%7.2f,%7.2f,%7.2f) %-7.2f %-14s %-14s %-10s" %
              (i, c[0], c[1], c[2], r, shown_t, shown_q, shown_e))
        lines.append((i, to_q(c[0]), to_q(c[1]), to_q(c[2]), to_q(r), hit, tq))

    print()
    print("spheres=%d  hits=%d  misses=%d" % (len(spheres), n_hit, len(spheres) - n_hit))
    print("max |Q16.16 - double| over the hits: %.3e  (1 LSB = %.3e)"
          % (max_err, 1.0 / ONE))

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "vectors.vh")
    with open(out, "w", newline="\n") as f:
        f.write("// Generated by hw/tb/gen_vectors.py -- do not edit by hand.\n")
        f.write("// Operands and expected results taken from the real raytrace scene.\n")
        f.write("localparam N_SPHERES = %d;\n\n" % len(spheres))
        f.write("// ray: origin and (pre-normalised) direction, Q16.16\n")
        for name, val in (("RAY_PX", ray_p[0]), ("RAY_PY", ray_p[1]), ("RAY_PZ", ray_p[2]),
                          ("RAY_VX", ray_v[0]), ("RAY_VY", ray_v[1]), ("RAY_VZ", ray_v[2])):
            f.write("localparam [31:0] %s = 32'h%08X;  // %+.9f\n" % (name, to_q(val), val))
        f.write("\n// spheres: {cx, cy, cz, r} and expected {hit, t}\n")
        f.write("reg [31:0] SPH_CX [0:N_SPHERES-1];\n")
        f.write("reg [31:0] SPH_CY [0:N_SPHERES-1];\n")
        f.write("reg [31:0] SPH_CZ [0:N_SPHERES-1];\n")
        f.write("reg [31:0] SPH_R  [0:N_SPHERES-1];\n")
        f.write("reg        EXP_HIT[0:N_SPHERES-1];\n")
        f.write("reg [31:0] EXP_T  [0:N_SPHERES-1];\n\n")
        f.write("task load_vectors; begin\n")
        for (i, cx, cy, cz, r, hit, tq) in lines:
            f.write("  SPH_CX[%d]=32'h%08X; SPH_CY[%d]=32'h%08X; SPH_CZ[%d]=32'h%08X; "
                    "SPH_R[%d]=32'h%08X; EXP_HIT[%d]=1'b%d; EXP_T[%d]=32'h%08X;\n"
                    % (i, cx, i, cy, i, cz, i, r, i, hit, i, tq))
        f.write("end endtask\n")
    print("\nwrote %s" % out)


if __name__ == "__main__":
    main()
